// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-OgoSWi_Hc1_4ypYs-CY2XJKT5ZMVOa4',
    appId: '1:886340850824:web:53c2d8ff91af9e4ac23b3d',
    messagingSenderId: '886340850824',
    projectId: 'e-waste-collector-dbd6d',
    authDomain: 'e-waste-collector-dbd6d.firebaseapp.com',
    storageBucket: 'e-waste-collector-dbd6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi7qybIsPm2dtfQaJJN_i26ifqSOAOaDU',
    appId: '1:886340850824:android:6f1a786303776190c23b3d',
    messagingSenderId: '886340850824',
    projectId: 'e-waste-collector-dbd6d',
    storageBucket: 'e-waste-collector-dbd6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASGEeLN39nSIOr_Z3mdUfmp9C3OMMa0W4',
    appId: '1:886340850824:ios:ceac6e96a5acb139c23b3d',
    messagingSenderId: '886340850824',
    projectId: 'e-waste-collector-dbd6d',
    storageBucket: 'e-waste-collector-dbd6d.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASGEeLN39nSIOr_Z3mdUfmp9C3OMMa0W4',
    appId: '1:886340850824:ios:ceac6e96a5acb139c23b3d',
    messagingSenderId: '886340850824',
    projectId: 'e-waste-collector-dbd6d',
    storageBucket: 'e-waste-collector-dbd6d.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdy0vKvr55zr2BjRKHGN6AsAE1OS4L5GY',
    appId: '1:886340850824:web:ae347356c1e3abeec23b3d',
    messagingSenderId: '886340850824',
    projectId: 'e-waste-collector-dbd6d',
    authDomain: 'e-waste-collector-dbd6d.firebaseapp.com',
    storageBucket: 'e-waste-collector-dbd6d.firebasestorage.app',
  );

}